spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.206:3306/MyWeiboDemo?serverTimezone=Asia/Shanghai&characterEncoding=utf8
  redis:
    host: 192.168.1.206
    port: 6379
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: org.eu.konworkers.myweibodemo.domain.pojo

