spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///MyWeiboDemo?serverTimezone=UTC
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

